// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManagementApi.Models;

#nullable disable

namespace StudentManagementApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260425012036_AddRoomSupportToClassSchedule")]
    partial class AddRoomSupportToClassSchedule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentManagementApi.Models.Account", b =>
                {
                    b.Property<string>("AccountId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("AccountID");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("AccountId")
                        .HasName("PK__Account__349DA586BA255435");

                    b.HasIndex(new[] { "Username" }, "IDX_Account_Username");

                    b.HasIndex(new[] { "Username" }, "UQ__Account__536C85E4F6150CF6")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__Account__A9D1053435979395")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("StudentManagementApi.Models.Advisor", b =>
                {
                    b.Property<string>("AdvisorId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("AdvisorID");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("AccountID");

                    b.Property<string>("DepartmentId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("DepartmentID");

                    b.HasKey("AdvisorId")
                        .HasName("PK__Advisor__9DE0B607CC65F88B");

                    b.HasIndex("DepartmentId");

                    b.HasIndex(new[] { "AccountId" }, "UQ__Advisor__349DA5878CDC9EF1")
                        .IsUnique();

                    b.ToTable("Advisor");
                });

            modelBuilder.Entity("StudentManagementApi.Models.AdvisorClass", b =>
                {
                    b.Property<int>("AdvisorClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AdvisorClassID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdvisorClassId"));

                    b.Property<int>("AcademicYear")
                        .HasColumnType("int");

                    b.Property<string>("AdvisorId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("AdvisorID");

                    b.Property<string>("ClassCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AdvisorClassId")
                        .HasName("PK__AdvisorC__97AE70D77B03A4AA");

                    b.HasIndex("AdvisorId");

                    b.HasIndex(new[] { "ClassCode" }, "UQ__AdvisorC__2ECD4A55C5294043")
                        .IsUnique();

                    b.ToTable("AdvisorClass");
                });

            modelBuilder.Entity("StudentManagementApi.Models.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AttendanceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<DateOnly>("AttendanceDate")
                        .HasColumnType("date");

                    b.Property<string>("ClassId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ClassID");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("StudentID");

                    b.HasKey("AttendanceId")
                        .HasName("PK__Attendan__8B69263CD3AA0686");

                    b.HasIndex(new[] { "ClassId", "AttendanceDate" }, "IDX_Attendance_Class_Date");

                    b.HasIndex(new[] { "StudentId", "ClassId", "AttendanceDate" }, "UQ_Attendance_Student_Class_Date")
                        .IsUnique();

                    b.ToTable("Attendance");
                });

            modelBuilder.Entity("StudentManagementApi.Models.Class", b =>
                {
                    b.Property<string>("ClassId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ClassID");

                    b.Property<string>("ClassCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("CurrentStudents")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("MaxStudents")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("ScheduleID");

                    b.Property<string>("SemesterId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SemesterID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("OPEN");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SubjectID");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("TeacherID");

                    b.HasKey("ClassId")
                        .HasName("PK__Class__CB1927A085263822");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.HasIndex(new[] { "ClassCode", "SemesterId" }, "UQ_Class_Code_Semester")
                        .IsUnique();

                    b.ToTable("Class");
                });

            modelBuilder.Entity("StudentManagementApi.Models.ClassSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ScheduleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("PeriodEnd")
                        .HasColumnType("int");

                    b.Property<int>("PeriodStart")
                        .HasColumnType("int");

                    b.Property<string>("Room")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Room");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("RoomID");

                    b.HasKey("ScheduleId")
                        .HasName("PK__ClassSch__9C8A5B69A92D038D");

                    b.HasIndex("RoomId");

                    b.ToTable("ClassSchedule", (string)null);
                });

            modelBuilder.Entity("StudentManagementApi.Models.CourseRegistration", b =>
                {
                    b.Property<int>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RegistrationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistrationId"));

                    b.Property<string>("ClassId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ClassID");

                    b.Property<DateTime?>("RegisteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("PENDING");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("StudentID");

                    b.HasKey("RegistrationId")
                        .HasName("PK__CourseRe__6EF58830D6374BD1");

                    b.HasIndex(new[] { "ClassId" }, "IDX_CourseRegistration_Class");

                    b.HasIndex(new[] { "StudentId" }, "IDX_CourseRegistration_Student");

                    b.HasIndex(new[] { "StudentId", "ClassId" }, "UQ_Registration_Student_Class")
                        .IsUnique();

                    b.ToTable("CourseRegistration");
                });

            modelBuilder.Entity("StudentManagementApi.Models.Curriculum", b =>
                {
                    b.Property<int>("CurriculumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CurriculumID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CurriculumId"));

                    b.Property<int>("CohortYear")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CurriculumCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("CurriculumName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DepartmentId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("DepartmentID");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<int>("TotalCredits")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("CurriculumId");

                    b.HasIndex(new[] { "CurriculumCode" }, "UQ_Curriculum_Code")
                        .IsUnique();

                    b.ToTable("Curriculum", (string)null);
                });

            modelBuilder.Entity("StudentManagementApi.Models.CurriculumSubject", b =>
                {
                    b.Property<int>("CurriculumSubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CurriculumSubjectID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CurriculumSubjectId"));

                    b.Property<int>("CurriculumId")
                        .HasColumnType("int")
                        .HasColumnName("CurriculumID");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("RecommendedSemester")
                        .HasColumnType("int");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SubjectID");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Bắt buộc");

                    b.HasKey("CurriculumSubjectId");

                    b.HasIndex(new[] { "CurriculumId", "SubjectId" }, "UQ_CurriculumSubject")
                        .IsUnique();

                    b.ToTable("CurriculumSubject", (string)null);
                });

            modelBuilder.Entity("StudentManagementApi.Models.Department", b =>
                {
                    b.Property<string>("DepartmentId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("DepartmentID");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("DepartmentId")
                        .HasName("PK__Departme__B2079BCD0CA48ACF");

                    b.HasIndex(new[] { "DepartmentCode" }, "UQ__Departme__6EA8896D47F2DF59")
                        .IsUnique();

                    b.ToTable("Department");
                });

            modelBuilder.Entity("StudentManagementApi.Models.Gpa", b =>
                {
                    b.Property<int>("Gpaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GPAID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Gpaid"));

                    b.Property<decimal>("CumulativeGpa")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnName("CumulativeGPA");

                    b.Property<decimal>("Gpa1")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnName("GPA");

                    b.Property<string>("SemesterId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SemesterID");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("StudentID");

                    b.Property<int>("TotalCreditsEarned")
                        .HasColumnType("int");

                    b.Property<int>("TotalCreditsRegistered")
                        .HasColumnType("int");

                    b.HasKey("Gpaid")
                        .HasName("PK__GPA__890CBEC478A60D8E");

                    b.HasIndex("SemesterId");

                    b.HasIndex(new[] { "StudentId", "SemesterId" }, "UQ_GPA_Student_Semester")
                        .IsUnique();

                    b.ToTable("GPA");
                });

            modelBuilder.Entity("StudentManagementApi.Models.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GradeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeId"));

                    b.Property<string>("ClassId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ClassID");

                    b.Property<decimal?>("FinalScore")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<bool?>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LetterGrade")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<decimal?>("MidtermScore")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("ProcessScore")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("StudentID");

                    b.Property<decimal?>("TotalScore")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("GradeId")
                        .HasName("PK__Grade__54F87A37571BC46D");

                    b.HasIndex("ClassId");

                    b.HasIndex(new[] { "StudentId" }, "IDX_Grade_Student");

                    b.HasIndex(new[] { "StudentId", "ClassId" }, "UQ_Grade_Student_Class")
                        .IsUnique();

                    b.ToTable("Grade");
                });

            modelBuilder.Entity("StudentManagementApi.Models.GraduationRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RequestID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<decimal>("CumulativeGpa")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnName("CumulativeGPA");

                    b.Property<bool>("MandatoryDone")
                        .HasColumnType("bit");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SemesterId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SemesterID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("Chờ xét duyệt");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("StudentID");

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("TotalCreditsEarned")
                        .HasColumnType("int");

                    b.Property<decimal>("TuitionDebt")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("RequestId")
                        .HasName("PK_GradRequest");

                    b.HasIndex("SemesterId");

                    b.HasIndex("StudentId");

                    b.ToTable("GraduationRequest", (string)null);
                });

            modelBuilder.Entity("StudentManagementApi.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NotificationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Manual");

                    b.Property<bool>("SendEmail")
                        .HasColumnType("bit");

                    b.Property<string>("SenderId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SenderID");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("TargetClassId")
                        .HasColumnType("int")
                        .HasColumnName("TargetClassID");

                    b.Property<string>("TargetScope")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("Individual");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("NotificationId");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("StudentManagementApi.Models.NotificationRecipient", b =>
                {
                    b.Property<int>("RecipientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RecipientID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipientId"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("AccountID");

                    b.Property<string>("EmailError")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("EmailSentAt")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsEmailSent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("NotificationId")
                        .HasColumnType("int")
                        .HasColumnName("NotificationID");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime");

                    b.HasKey("RecipientId")
                        .HasName("PK_NotifRecipient");

                    b.HasIndex("NotificationId");

                    b.ToTable("NotificationRecipient", (string)null);
                });

            modelBuilder.Entity("StudentManagementApi.Models.Prerequisite", b =>
                {
                    b.Property<int>("PrerequisiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PrerequisiteID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrerequisiteId"));

                    b.Property<string>("RequiredSubjectId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("RequiredSubjectID");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SubjectID");

                    b.HasKey("PrerequisiteId")
                        .HasName("PK__Prerequi__25A953F931AA033D");

                    b.HasIndex("RequiredSubjectId");

                    b.HasIndex(new[] { "SubjectId", "RequiredSubjectId" }, "UQ_Prerequisite")
                        .IsUnique();

                    b.ToTable("Prerequisite");
                });

            modelBuilder.Entity("StudentManagementApi.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoomID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<string>("Building")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Lý thuyết");

                    b.HasKey("RoomId");

                    b.HasIndex(new[] { "RoomCode" }, "UQ_Room_Code")
                        .IsUnique();

                    b.ToTable("Room", (string)null);
                });

            modelBuilder.Entity("StudentManagementApi.Models.Semester", b =>
                {
                    b.Property<string>("SemesterId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SemesterID");

                    b.Property<int>("AcademicYear")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool?>("IsRegistrationOpen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Room")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("RoomID");

                    b.Property<string>("SemesterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SemesterNumber")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("SemesterId")
                        .HasName("PK__Semester__043301BD6880DC52");

                    b.ToTable("Semester");
                });

            modelBuilder.Entity("StudentManagementApi.Models.Student", b =>
                {
                    b.Property<string>("StudentId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("StudentID");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("AccountID");

                    b.Property<int>("AdmissionYear")
                        .HasColumnType("int");

                    b.Property<int>("AdvisorClassId")
                        .HasColumnType("int")
                        .HasColumnName("AdvisorClassID");

                    b.Property<string>("Major")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("StudentId")
                        .HasName("PK__Student__32C52A792E213A55");

                    b.HasIndex("AdvisorClassId");

                    b.HasIndex(new[] { "StudentCode" }, "IDX_Student_StudentCode");

                    b.HasIndex(new[] { "StudentCode" }, "UQ__Student__1FC88604A2B4E75B")
                        .IsUnique();

                    b.HasIndex(new[] { "AccountId" }, "UQ__Student__349DA5870B73DB3B")
                        .IsUnique();

                    b.ToTable("Student");
                });

            modelBuilder.Entity("StudentManagementApi.Models.Subject", b =>
                {
                    b.Property<string>("SubjectId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SubjectID");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("DepartmentId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("DepartmentID");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SubjectId")
                        .HasName("PK__Subject__AC1BA388479791E9");

                    b.HasIndex("DepartmentId");

                    b.HasIndex(new[] { "SubjectCode" }, "UQ__Subject__9F7CE1A9C4C50C97")
                        .IsUnique();

                    b.ToTable("Subject");
                });

            modelBuilder.Entity("StudentManagementApi.Models.SystemConfig", b =>
                {
                    b.Property<string>("ConfigKey")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ConfigKey")
                        .HasName("PK__SystemCo__4A306785FE778B6A");

                    b.ToTable("SystemConfig");
                });

            modelBuilder.Entity("StudentManagementApi.Models.Teacher", b =>
                {
                    b.Property<string>("TeacherId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("TeacherID");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("AccountID");

                    b.Property<string>("DepartmentId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("DepartmentID");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TeacherId")
                        .HasName("PK__Teacher__EDF25944607BD03F");

                    b.HasIndex("DepartmentId");

                    b.HasIndex(new[] { "AccountId" }, "UQ__Teacher__349DA58773146516")
                        .IsUnique();

                    b.ToTable("Teacher");
                });

            modelBuilder.Entity("StudentManagementApi.Models.Tuition", b =>
                {
                    b.Property<int>("TuitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TuitionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TuitionId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("FeeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SemesterId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SemesterID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("Chưa đóng");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("StudentID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("TuitionId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("StudentId");

                    b.ToTable("Tuition", (string)null);
                });

            modelBuilder.Entity("StudentManagementApi.Models.TuitionPayment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PaymentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("AmountSubmitted")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("EvidenceFile")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("ReviewedBy");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("Chờ duyệt");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("StudentID");

                    b.Property<int>("TuitionId")
                        .HasColumnType("int")
                        .HasColumnName("TuitionID");

                    b.HasKey("PaymentId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TuitionId");

                    b.ToTable("TuitionPayment", (string)null);
                });

            modelBuilder.Entity("StudentManagementApi.Models.Warning", b =>
                {
                    b.Property<int>("WarningId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("WarningID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WarningId"));

                    b.Property<string>("IssuedBy")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("IssuedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ResolutionNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SemesterId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SemesterID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("ACTIVE");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("StudentID");

                    b.Property<int>("WarningLevel")
                        .HasColumnType("int");

                    b.Property<string>("WarningReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("WarningId")
                        .HasName("PK__Warning__214571B8F15D8838");

                    b.HasIndex("IssuedBy");

                    b.HasIndex("SemesterId");

                    b.HasIndex(new[] { "StudentId", "SemesterId" }, "IDX_Warning_Student_Semester");

                    b.ToTable("Warning");
                });

            modelBuilder.Entity("StudentManagementApi.Models.Advisor", b =>
                {
                    b.HasOne("StudentManagementApi.Models.Account", "Account")
                        .WithOne("Advisor")
                        .HasForeignKey("StudentManagementApi.Models.Advisor", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Advisor__Account__44FF419A");

                    b.HasOne("StudentManagementApi.Models.Department", "Department")
                        .WithMany("Advisors")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("FK__Advisor__Departm__45F365D3");

                    b.Navigation("Account");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("StudentManagementApi.Models.AdvisorClass", b =>
                {
                    b.HasOne("StudentManagementApi.Models.Advisor", "Advisor")
                        .WithMany("AdvisorClasses")
                        .HasForeignKey("AdvisorId")
                        .IsRequired()
                        .HasConstraintName("FK__AdvisorCl__Advis__49C3F6B7");

                    b.Navigation("Advisor");
                });

            modelBuilder.Entity("StudentManagementApi.Models.Attendance", b =>
                {
                    b.HasOne("StudentManagementApi.Models.Class", "Class")
                        .WithMany("Attendances")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Attendanc__Class__7B5B524B");

                    b.HasOne("StudentManagementApi.Models.Student", "Student")
                        .WithMany("Attendances")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Attendanc__Stude__7C4F7684");

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentManagementApi.Models.Class", b =>
                {
                    b.HasOne("StudentManagementApi.Models.ClassSchedule", "Schedule")
                        .WithMany("Classes")
                        .HasForeignKey("ScheduleId")
                        .IsRequired()
                        .HasConstraintName("FK__Class__ScheduleI__6C190EBB");

                    b.HasOne("StudentManagementApi.Models.Semester", "Semester")
                        .WithMany("Classes")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Class__SemesterI__6B24EA82");

                    b.HasOne("StudentManagementApi.Models.Subject", "Subject")
                        .WithMany("Classes")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Class__SubjectID__693CA210");

                    b.HasOne("StudentManagementApi.Models.Teacher", "Teacher")
                        .WithMany("Classes")
                        .HasForeignKey("TeacherId")
                        .IsRequired()
                        .HasConstraintName("FK__Class__TeacherID__6A30C649");

                    b.Navigation("Schedule");

                    b.Navigation("Semester");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("StudentManagementApi.Models.ClassSchedule", b =>
                {
                    b.HasOne("StudentManagementApi.Models.Room", null)
                        .WithMany("ClassSchedules")
                        .HasForeignKey("RoomId");
                });

            modelBuilder.Entity("StudentManagementApi.Models.CourseRegistration", b =>
                {
                    b.HasOne("StudentManagementApi.Models.Class", "Class")
                        .WithMany("CourseRegistrations")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK__CourseReg__Class__74AE54BC");

                    b.HasOne("StudentManagementApi.Models.Student", "Student")
                        .WithMany("CourseRegistrations")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__CourseReg__Stude__73BA3083");

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentManagementApi.Models.CurriculumSubject", b =>
                {
                    b.HasOne("StudentManagementApi.Models.Curriculum", "Curriculum")
                        .WithMany("CurriculumSubjects")
                        .HasForeignKey("CurriculumId")
                        .IsRequired()
                        .HasConstraintName("FK_CurrSub_Curriculum");

                    b.Navigation("Curriculum");
                });

            modelBuilder.Entity("StudentManagementApi.Models.Gpa", b =>
                {
                    b.HasOne("StudentManagementApi.Models.Semester", "Semester")
                        .WithMany("Gpas")
                        .HasForeignKey("SemesterId")
                        .IsRequired()
                        .HasConstraintName("FK__GPA__SemesterID__0B91BA14");

                    b.HasOne("StudentManagementApi.Models.Student", "Student")
                        .WithMany("Gpas")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__GPA__StudentID__0A9D95DB");

                    b.Navigation("Semester");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentManagementApi.Models.Grade", b =>
                {
                    b.HasOne("StudentManagementApi.Models.Class", "Class")
                        .WithMany("Grades")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Grade__ClassID__02084FDA");

                    b.HasOne("StudentManagementApi.Models.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Grade__StudentID__01142BA1");

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentManagementApi.Models.GraduationRequest", b =>
                {
                    b.HasOne("StudentManagementApi.Models.Semester", "Semester")
                        .WithMany("GraduationRequests")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagementApi.Models.Student", "Student")
                        .WithMany("GraduationRequests")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Semester");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentManagementApi.Models.NotificationRecipient", b =>
                {
                    b.HasOne("StudentManagementApi.Models.Notification", "Notification")
                        .WithMany("NotificationRecipients")
                        .HasForeignKey("NotificationId")
                        .IsRequired()
                        .HasConstraintName("FK_NotifRecip_Notification");

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("StudentManagementApi.Models.Prerequisite", b =>
                {
                    b.HasOne("StudentManagementApi.Models.Subject", "RequiredSubject")
                        .WithMany("PrerequisiteRequiredSubjects")
                        .HasForeignKey("RequiredSubjectId")
                        .IsRequired()
                        .HasConstraintName("FK__Prerequis__Requi__5DCAEF64");

                    b.HasOne("StudentManagementApi.Models.Subject", "Subject")
                        .WithMany("PrerequisiteSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Prerequis__Subje__5CD6CB2B");

                    b.Navigation("RequiredSubject");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("StudentManagementApi.Models.Student", b =>
                {
                    b.HasOne("StudentManagementApi.Models.Account", "Account")
                        .WithOne("Student")
                        .HasForeignKey("StudentManagementApi.Models.Student", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Student__Account__4E88ABD4");

                    b.HasOne("StudentManagementApi.Models.AdvisorClass", "AdvisorClass")
                        .WithMany("Students")
                        .HasForeignKey("AdvisorClassId")
                        .IsRequired()
                        .HasConstraintName("FK__Student__Advisor__4F7CD00D");

                    b.Navigation("Account");

                    b.Navigation("AdvisorClass");
                });

            modelBuilder.Entity("StudentManagementApi.Models.Subject", b =>
                {
                    b.HasOne("StudentManagementApi.Models.Department", "Department")
                        .WithMany("Subjects")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("FK__Subject__Departm__59063A47");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("StudentManagementApi.Models.Teacher", b =>
                {
                    b.HasOne("StudentManagementApi.Models.Account", "Account")
                        .WithOne("Teacher")
                        .HasForeignKey("StudentManagementApi.Models.Teacher", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Teacher__Account__534D60F1");

                    b.HasOne("StudentManagementApi.Models.Department", "Department")
                        .WithMany("Teachers")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("FK__Teacher__Departm__5441852A");

                    b.Navigation("Account");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("StudentManagementApi.Models.Tuition", b =>
                {
                    b.HasOne("StudentManagementApi.Models.Semester", "Semester")
                        .WithMany("Tuitions")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagementApi.Models.Student", "Student")
                        .WithMany("Tuitions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Semester");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentManagementApi.Models.TuitionPayment", b =>
                {
                    b.HasOne("StudentManagementApi.Models.Student", "Student")
                        .WithMany("TuitionPayments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentManagementApi.Models.Tuition", "Tuition")
                        .WithMany("TuitionPayments")
                        .HasForeignKey("TuitionId")
                        .IsRequired()
                        .HasConstraintName("FK_TuitionPay_Tuition");

                    b.Navigation("Student");

                    b.Navigation("Tuition");
                });

            modelBuilder.Entity("StudentManagementApi.Models.Warning", b =>
                {
                    b.HasOne("StudentManagementApi.Models.Advisor", "IssuedByNavigation")
                        .WithMany("Warnings")
                        .HasForeignKey("IssuedBy")
                        .HasConstraintName("FK__Warning__IssuedB__114A936A");

                    b.HasOne("StudentManagementApi.Models.Semester", "Semester")
                        .WithMany("Warnings")
                        .HasForeignKey("SemesterId")
                        .IsRequired()
                        .HasConstraintName("FK__Warning__Semeste__0F624AF8");

                    b.HasOne("StudentManagementApi.Models.Student", "Student")
                        .WithMany("Warnings")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Warning__Student__0E6E26BF");

                    b.Navigation("IssuedByNavigation");

                    b.Navigation("Semester");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentManagementApi.Models.Account", b =>
                {
                    b.Navigation("Advisor");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("StudentManagementApi.Models.Advisor", b =>
                {
                    b.Navigation("AdvisorClasses");

                    b.Navigation("Warnings");
                });

            modelBuilder.Entity("StudentManagementApi.Models.AdvisorClass", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("StudentManagementApi.Models.Class", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("CourseRegistrations");

                    b.Navigation("Grades");
                });

            modelBuilder.Entity("StudentManagementApi.Models.ClassSchedule", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("StudentManagementApi.Models.Curriculum", b =>
                {
                    b.Navigation("CurriculumSubjects");
                });

            modelBuilder.Entity("StudentManagementApi.Models.Department", b =>
                {
                    b.Navigation("Advisors");

                    b.Navigation("Subjects");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("StudentManagementApi.Models.Notification", b =>
                {
                    b.Navigation("NotificationRecipients");
                });

            modelBuilder.Entity("StudentManagementApi.Models.Room", b =>
                {
                    b.Navigation("ClassSchedules");
                });

            modelBuilder.Entity("StudentManagementApi.Models.Semester", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Gpas");

                    b.Navigation("GraduationRequests");

                    b.Navigation("Tuitions");

                    b.Navigation("Warnings");
                });

            modelBuilder.Entity("StudentManagementApi.Models.Student", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("CourseRegistrations");

                    b.Navigation("Gpas");

                    b.Navigation("Grades");

                    b.Navigation("GraduationRequests");

                    b.Navigation("TuitionPayments");

                    b.Navigation("Tuitions");

                    b.Navigation("Warnings");
                });

            modelBuilder.Entity("StudentManagementApi.Models.Subject", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("PrerequisiteRequiredSubjects");

                    b.Navigation("PrerequisiteSubjects");
                });

            modelBuilder.Entity("StudentManagementApi.Models.Teacher", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("StudentManagementApi.Models.Tuition", b =>
                {
                    b.Navigation("TuitionPayments");
                });
#pragma warning restore 612, 618
        }
    }
}
